server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warn?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver